// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flntbvwncrjajjkeywrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsbnRidnduY3JqYWpqa2V5d3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTk2MTQsImV4cCI6MjA2NTczNTYxNH0.k00ORbKgRsFsMs6C4HnZH2-C5ph7-xjGnAesbnJ3ifw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});